import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

export interface BrowserCookie {
  domain?: string;
  path?: string;
  secure?: boolean;
  expirationDate?: number;
  name?: string;
  value?: string;
  httpOnly?: boolean;
}

export function cookieFilePath(): string {
  return path.join(
    os.homedir(),
    ".config",
    "opencode",
    "credentials",
    "youtube-transcript",
    "cookies.youtube.txt",
  );
}

export async function saveYouTubeCookies(cookies: BrowserCookie[]): Promise<{ path: string; count: number }> {
  const usable = cookies.filter((cookie) =>
    Boolean(cookie.name)
    && typeof cookie.value === "string"
    && /(^|\.)youtube\.com$/i.test(String(cookie.domain || "").replace(/^\./, "")),
  );
  if (!usable.length) throw new Error("COOKIE_MISSING: 没有收到可用的 YouTube Cookie，请先在 Chrome 登录 YouTube。");

  const lines = ["# Netscape HTTP Cookie File", "# Generated by YouTube Note Reader. Do not edit.", ""];
  for (const cookie of usable) {
    const rawDomain = String(cookie.domain || ".youtube.com");
    const domain = `${cookie.httpOnly ? "#HttpOnly_" : ""}${rawDomain}`;
    lines.push([
      domain,
      rawDomain.startsWith(".") ? "TRUE" : "FALSE",
      cookie.path || "/",
      cookie.secure ? "TRUE" : "FALSE",
      Math.max(0, Math.floor(Number(cookie.expirationDate) || 0)),
      cookie.name,
      cookie.value,
    ].join("\t"));
  }

  const target = cookieFilePath();
  await fs.mkdir(path.dirname(target), { recursive: true });
  const temporary = `${target}.${process.pid}.tmp`;
  await fs.writeFile(temporary, `${lines.join("\n")}\n`, { encoding: "utf8", mode: 0o600 });
  await fs.rename(temporary, target);
  return { path: target, count: usable.length };
}
